package main

import (
	"log"
	"strings"

	"go.uber.org/zap"
)

// NexusRouter API 网关（OpenAI 兼容 Chat Completions 反向代理）。
func main() {
	app, err := InitializeApp()
	if err != nil {
		log.Fatalf("初始化失败: %v", err)
	}
	defer func(l *zap.Logger) { _ = l.Sync() }(app.Log)

	addr := ":8080"
	if app.Config != nil && strings.TrimSpace(app.Config.HTTPListenAddr) != "" {
		addr = strings.TrimSpace(app.Config.HTTPListenAddr)
	}
	if app.Config != nil && app.Config.AdminJWTSecretAutoGenerated {
		app.Log.Warn("未设置 NEXUSROUTER_ADMIN_JWT_SECRET，已自动生成随机 UUID 密钥；生产环境请显式配置，否则重启后管理端 JWT 将失效")
	}
	app.Log.Info("网关启动", zap.String("addr", addr))
	if err := app.Run(); err != nil {
		app.Log.Fatal("服务退出", zap.Error(err))
	}
}
