// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/NexusRouter/nexusrouter/services/gateway/internal/app"
	"github.com/NexusRouter/nexusrouter/services/gateway/internal/provider"
)

// Injectors from wire.go:

func InitializeApp() (*app.Application, error) {
	logger, err := provider.ProvideLogger()
	if err != nil {
		return nil, err
	}
	engine := provider.ProvideEngine(logger)
	application := app.NewApplication(logger, engine)
	return application, nil
}
