// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/NexusRouter/nexusrouter/services/gateway/internal/app"
	"github.com/NexusRouter/nexusrouter/services/gateway/internal/provider"
)

// Injectors from wire.go:

func InitializeApp() (*app.Application, error) {
	logger, err := provider.ProvideLogger()
	if err != nil {
		return nil, err
	}
	config := provider.ProvideConfig()
	db, err := provider.ProvideDB(config, logger)
	if err != nil {
		return nil, err
	}
	store, err := provider.ProvideKeyStore(config, logger, db)
	if err != nil {
		return nil, err
	}
	runtimeStore, err := provider.ProvideRuntimeStore(config, db)
	if err != nil {
		return nil, err
	}
	collector := provider.ProvideMetrics()
	engine := provider.ProvideEngine(logger, config, store, runtimeStore, collector, db)
	application := app.NewApplication(logger, engine, store, runtimeStore, config, collector)
	return application, nil
}
