package config

import (
	"strings"
	"testing"
)

// TestLoad_ReturnsNonNil 默认环境变量下 Load 返回可用配置对象。
func TestLoad_ReturnsNonNil(t *testing.T) {
	cfg := Load()
	if cfg == nil {
		t.Fatal("Load() 返回 nil")
	}
	if cfg.HTTPListenAddr == "" {
		t.Fatal("HTTPListenAddr 为空")
	}
}

func TestLoad_AdminConsoleExplicitFalse(t *testing.T) {
	t.Setenv("NEXUSROUTER_ENABLE_ADMIN_CONSOLE", "false")
	cfg := Load()
	if cfg.EnableAdminConsole {
		t.Fatal("expected EnableAdminConsole false when env is false")
	}
}

func TestLoad_AutoGeneratesJWTWhenSecretUnset(t *testing.T) {
	t.Setenv("NEXUSROUTER_ADMIN_JWT_SECRET", "")
	cfg := Load()
	if cfg.AdminJWTSecret == "" {
		t.Fatal("expected auto-generated AdminJWTSecret")
	}
	if !cfg.AdminJWTSecretAutoGenerated {
		t.Fatal("AdminJWTSecretAutoGenerated")
	}
	if len(cfg.AdminJWTSecret) != 36 || strings.Count(cfg.AdminJWTSecret, "-") != 4 {
		t.Fatalf("expected UUID v4 shape, got %q", cfg.AdminJWTSecret)
	}
}
